---
name: Tests

on: [push, pull_request]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    strategy:
      matrix:
        rocq_container:
        - rocq/rocq-prover:9.0.1-ocaml-4.14.2-flambda
    container:
      image: ${{ matrix.rocq_container }}
      options: --user root
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Fix permissions
      run: chown -R 1000 .
    - name: ls
      run: ls -la .
    - name: Install Opam dependencies
      run: su rocq -c 'eval $(opam env) && opam install --deps-only --with-test --with-doc -y -j 2 ./Formal_ML.opam'
    - name: Build using Make
      run: su rocq -c 'eval $(opam env) && make -kj 2'
    - name: Build documentation
      run: su rocq -c 'eval $(opam env) && make -kj 2 doc'
